### ISSUE TITLE
Build Errors when trying to install via NPM

### ISSUE THREAD

**Issue by octo-kumo** [sjoerd108/jimp-native#1]
Hello when trying to install, i receive the following error from npm
```
crop.obj : error LNK2019: unresolved external symbol "double __cdecl diff(unsigned char *,unsigned char *)" (?diff@@YANPEAE0@Z) referenced in function "void __cdecl autocrop(class Image &,long,double,bool,bool,bool,bool,bool,bool,long &,long &)" (?autocrop@@YAXAEAVImage@@JN_N11111AEAJ2@Z)[C:\...\node_modules\jimp-native\build\jimp-native.vcxproj]
image.obj : error LNK2019: unresolved external symbol "void __cdecl clipColour(struct ColourFP &)" (?clipColour@@YAXAEAUColourFP@@@Z) referenced in function "public: void __cdecl Image::setColourAt(long,long,struct ColourFP,enum EdgeHandling)" (?setColourAt@Image@@QEAAXJJUColourFP@@W4EdgeHandling@@@Z) [C:\...\node_modules\jimp-native\build\jimp-native.vcxproj]
C:\...\node_modules\jimp-native\build\Release\jimp-native.node : fatal error LNK1120: 2 unresolved externals [C:\...\node_modules\jimp-native\build\jimp-native.vcxproj]

gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\zy\Documents\GitHub\e-notes\backend\node_modules\jimp-native
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by sjoerdthedev** [comment]
Hi thanks for letting me know! The module was developed on a Linux system so I've not spent much time trying to get it to build right for Windows. I'll boot up a VM and see what I can do :)

**Comment by sjoerdthedev** [comment]
Hey @octo-kumo could you give it another go? I've pushed a new version to NPM that should fix the issue you're having (tested on Windows 8.1 w/ MSBUILD 2019). Be sure to get v0.0.4.

Thanks for checking out the module!
